#creating PV is K8S Admin job
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  capacity:
    storage: 15Gi 
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # retain means don't delete data, Recycle means delete data don't delete disk. Delete means delete the disk
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0736a265fc51e02fe
  