apiVersion: v1
kind: Pod
metadata:
  name: nginx
  Namespace: roboshop-dev
  labels:
    name: nginx
    project: roboshop
specs:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80