apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    project: roboshop
    environment: development
    version: v1
    component: frontend
spec:
  containers:
  - name: nginx
    image: nginx