apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    project: roboshop
    component: cart
  ports:
    - protocol: TCP
      port: 80 #service port
      targetPort: 80 #containeer port
