apiVersion: v1
kind: Service
metadata:
  name: np-service
spec:
  type: NodePort
  selector:
    component: user
    environment: testing/QA
  ports:
   - protocol: TCP
     port: 80 #service port
     targetPort: 80 #containerport
