apiVersion: v1
kind: Service
metadata:
  name: service-lb
spec:
  type: LoadBalancer
  selector:
    component: shipping
    environment: prod
    purpose: loadbalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30005