apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels: #these are deployment labels
    purpose: rs-demo
    project: roboshop
spec:
  replicas: 3
  selector:
    matchLabels: #these labels are used to select pods
      purpose: rs-demo
      project: roboshop
  template: #pod definition
    metadata:
      labels:
        purpose: rs-demo
        project: roboshop
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80